name: Update README

on:
  workflow_dispatch:
  push:
  schedule:
            # ┌───────────── minute (0 - 59)
            # │ ┌───────────── hour (0 - 23)
            # │ │  ┌───────────── day of the month (1 - 31)
            # │ │  │  ┌───────────── month (1 - 12)
            # │ │  │  │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
            # │ │  │  │ │                                   7 is also Sunday on some systems)
    - cron: "14 3 */3 * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-snake.svg
            github-snake-dark.svg?palette=github-dark&color_snake=#5bcdec
      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          commit_message: 'docs: Update generated README'
          branch: main
